# Generated by Django 3.2 on 2021-04-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='Картинка')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст новости')),
                ('file', models.FileField(blank=True, upload_to='file', verbose_name='Файл')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('category', models.CharField(choices=[('education', 'образование'), ('entertainment', 'развлечение')], default='entertainment', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
